version: "2"

services:
   postgis:
      image: mdillon/postgis
      ports:
         - "55432:5432"
      environment:
         - POSTGRES_PASSWORD=docker
   geoserver:
      image: kartoza/geoserver
      ports:
         - "58080:8080"

